# These are supported funding model platforms

github: reiyy
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: lanraragi_cn
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
