on: 
  push:
    branches:
    - dev
    - test-builds
    - actions-testing
name: Continuous Delivery 
jobs:
  buildDevDocker:
    name: 构建并提交Docker镜像(Dev)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - uses: actions/cache@v4
      with: 
        path: /tmp/buildxcache
        key: ${{ runner.os }}-docker-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-buildx-
    - name: Docker 登录
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin
    - name: 构建/推送 LANraragi for Docker Dev
      run: |
        docker buildx build \
          --platform linux/386,linux/amd64,linux/arm64 \
          --output "type=image,push=true" \
          --tag yareiy/lanraragi_cn:dev \
          --cache-from "type=local,src=/tmp/buildxcache" \
          --cache-to "type=local,dest=/tmp/buildxcache" \
          --file ./tools/build/docker/Dockerfile .